.variables_cn: &variables_cn
  SHARED_SERVICES_ACCOUNT: 068946021388
  ECR_REGION: cn-northwest-1
  AWS_DOMAIN: amazonaws.com.cn

include:
  - project: 'd9/infrastructure/gitlab-ci-templates'
    ref: master
    file: '.k8s-nodejs-gitlab-ci-template.yml'
  - project: 'D9/infrastructure/gitlab-ci-templates'
    ref: master
    file: '.k8s-nodejs-gitlab-ci-template-cn.patch.yml'

install:
  stage: install
  image: node:21-alpine3.18
  script:
    - npm config set registry https://registry.npmmirror.com/
    - npm i pnpm -g
    - pnpm i
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/
  tags:
    - rms-cn-dev

audit:
  stage: validate
  image: node:21-alpine3.18
  script:
    - npm config set registry https://registry.npmmirror.com/
    - npm i pnpm -g
    - pnpm i --lockfile-only
    - npm config set registry https://registry.npmjs.org/
    - pnpm audit
  tags:
    - rms-cn-dev

lint:
  stage: validate
  image: node:21-alpine3.18
  script:
    - npm config set registry https://registry.npmmirror.com/
    - npm i pnpm -g
    - pnpm run lint
  tags:
    - rms-cn-dev

# unittests:
#   stage: validate
#   image: node:21-alpine3.18
#   dependencies:
#     - install
#   allow_failure: true
#   script:
#     - npm config set registry https://registry.npmmirror.com/
#     - npm i pnpm -g
#     - pnpm run test.coverage
#   artifacts:
#     paths:
#       - coverage
#       - coverage/lcov.info
#     when: always
#   coverage: '/^All files\s+\|\s+(\d+\.*\d*)\s+\|/'

#################
#     BUILD     #
#################

# Pulled in from .k8s-base-gitlab-ci-template.yml

build_image_aws_cn:
  tags:
    - rms-cn-dev
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: "$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH"
      when: on_success

trivy_cn:
  extends: trivy
  needs:
    - build_image_aws_cn
  image:
    name: 068946021388.dkr.ecr.cn-northwest-1.amazonaws.com.cn/aquasec/trivy:latest
    entrypoint: ['']
  variables: *variables_cn
  before_script:
    # - apk add curl
    - curl -sSfo global_trivyignore "${TEMPLATE_PAGES_URL}/trivyignore"
    - cat global_trivyignore >> ${CI_PROJECT_DIR}/.trivyignore
  script:
    # cache cleanup is needed when scanning images with the same tags, it does not remove the database
    - trivy image --clear-cache # trivy cache folder is .trivycache
    - trivy image --download-db-only --username AWS --password $(aws ecr get-login-password)
      --db-repository 068946021388.dkr.ecr.cn-northwest-1.amazonaws.com.cn/ghcr.io/aquasecurity/trivy-db
    - trivy image --download-java-db-only --username AWS --password $(aws ecr get-login-password)
      --java-db-repository 068946021388.dkr.ecr.cn-northwest-1.amazonaws.com.cn/ghcr.io/aquasecurity/trivy-java-db
    - trivy image --username AWS --password $(aws ecr get-login-password) --skip-db-update --skip-java-db-update
      --exit-code 0 --no-progress --format json --output "$CI_PROJECT_DIR/trivy-container-scan.json"
      "${KANIKO_IMAGE_TAG}:${CI_COMMIT_SHA}"
    - trivy image --username AWS --password $(aws ecr get-login-password) --skip-db-update --skip-java-db-update
      --exit-code 0 --no-progress "${KANIKO_IMAGE_TAG}:${CI_COMMIT_SHA}"
    - trivy image --username AWS --password $(aws ecr get-login-password) --skip-db-update --skip-java-db-update
      --exit-code 1 --no-progress --severity "$TRIVY_FAIL_THRESHOLD" "${KANIKO_IMAGE_TAG}:${CI_COMMIT_SHA}"
    # - ls -la ./ && ls -la .trivycache
  tags:
    - rms-cn-dev

# Pulled in from security/.k8s-base-sec-gitlab-ci-template.yml
config_validation:
  allow_failure: true

build_image_aws:
  rules:
    - when: never

sonarqube:
  allow_failure: true

deploy_aws_dev:
  rules:
    - when: never

deploy_aws_cn_dev:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: "$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH"
      when: on_success

trivy:
  rules:
    - when: never

deploy_aws_preprod:
  rules:
    - when: never

deploy_aws_prod:
  rules:
    - when: never

snyk-dev-upload:
  rules:
    - when: never

snyk-preprod-upload:
  rules:
    - when: never

snyk-production-upload:
  rules:
    - when: never

e2e_test:
  rules:
    - when: never
